//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThumbnailCreatorBot {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ThumbnailCreatorBot.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add text.
        /// </summary>
        internal static string AddText {
            get {
                return ResourceManager.GetString("AddText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled!.
        /// </summary>
        internal static string Canceled {
            get {
                return ResourceManager.GetString("Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose border color.
        /// </summary>
        internal static string ChooseBorderColor {
            get {
                return ResourceManager.GetString("ChooseBorderColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose font.
        /// </summary>
        internal static string ChooseFont {
            get {
                return ResourceManager.GetString("ChooseFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose horizontal alignment.
        /// </summary>
        internal static string ChooseHorizontalAlignment {
            get {
                return ResourceManager.GetString("ChooseHorizontalAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose formatting options, or add your text..
        /// </summary>
        internal static string ChooseOptionsOrAddText {
            get {
                return ResourceManager.GetString("ChooseOptionsOrAddText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose text color.
        /// </summary>
        internal static string ChooseTextColor {
            get {
                return ResourceManager.GetString("ChooseTextColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose text size.
        /// </summary>
        internal static string ChooseTextSize {
            get {
                return ResourceManager.GetString("ChooseTextSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose text style.
        /// </summary>
        internal static string ChooseTextStyle {
            get {
                return ResourceManager.GetString("ChooseTextStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose vertical alignment.
        /// </summary>
        internal static string ChooseVerticalAlignment {
            get {
                return ResourceManager.GetString("ChooseVerticalAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here is the configuration data for the last text item. What now?.
        /// </summary>
        internal static string ConfigurationOutput {
            get {
                return ResourceManager.GetString("ConfigurationOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the HTML color (e.g., #000000).
        /// </summary>
        internal static string EnterHtmlColor {
            get {
                return ResourceManager.GetString("EnterHtmlColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter text size.
        /// </summary>
        internal static string EnterTextSize {
            get {
                return ResourceManager.GetString("EnterTextSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThumbnailCreatorBot encountered an error. Would you like to report this? y/n.
        /// </summary>
        internal static string ErrorEncountered {
            get {
                return ResourceManager.GetString("ErrorEncountered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error successfully reported!.
        /// </summary>
        internal static string ErrorReported {
            get {
                return ResourceManager.GetString("ErrorReported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export last text settings.
        /// </summary>
        internal static string ExportConfiguration {
            get {
                return ResourceManager.GetString("ExportConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here is your finished thumbnail!.
        /// </summary>
        internal static string FinishedThumbnail {
            get {
                return ResourceManager.GetString("FinishedThumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid color. Try again..
        /// </summary>
        internal static string InvalidColor {
            get {
                return ResourceManager.GetString("InvalidColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received caption with image, but it was not in the proper format. Proceeding with standard procedure..
        /// </summary>
        internal static string InvalidConfiguration {
            get {
                return ResourceManager.GetString("InvalidConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid padding value. Try again..
        /// </summary>
        internal static string InvalidPadding {
            get {
                return ResourceManager.GetString("InvalidPadding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid size. Try again..
        /// </summary>
        internal static string InvalidSize {
            get {
                return ResourceManager.GetString("InvalidSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got the image! What would you like to do now?.
        /// </summary>
        internal static string ReceivedImage {
            get {
                return ResourceManager.GetString("ReceivedImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a font.
        /// </summary>
        internal static string SelectAFont {
            get {
                return ResourceManager.GetString("SelectAFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a text style.
        /// </summary>
        internal static string SelectATextStyle {
            get {
                return ResourceManager.GetString("SelectATextStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select horizontal alignment.
        /// </summary>
        internal static string SelectHorizontalAlignment {
            get {
                return ResourceManager.GetString("SelectHorizontalAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select vertical alignment.
        /// </summary>
        internal static string SelectVerticalAlignment {
            get {
                return ResourceManager.GetString("SelectVerticalAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set border thickness.
        /// </summary>
        internal static string SetBorderThickness {
            get {
                return ResourceManager.GetString("SetBorderThickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set horizontal padding.
        /// </summary>
        internal static string SetHorizontalPadding {
            get {
                return ResourceManager.GetString("SetHorizontalPadding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set text.
        /// </summary>
        internal static string SetText {
            get {
                return ResourceManager.GetString("SetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set vertical padding.
        /// </summary>
        internal static string SetVerticalPadding {
            get {
                return ResourceManager.GetString("SetVerticalPadding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What do you want to do now?.
        /// </summary>
        internal static string WhatNow {
            get {
                return ResourceManager.GetString("WhatNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What text do you want to add?.
        /// </summary>
        internal static string WhatTextToAdd {
            get {
                return ResourceManager.GetString("WhatTextToAdd", resourceCulture);
            }
        }
    }
}
